### ISSUE TITLE
Mic and audio playback don't work anymore

### ISSUE THREAD

**Issue by tomKPZ** [Jrawke/mumbleExpress#27]

**Comment by Jrawke** [comment]
Steps to reproduce? Working on my end.

**Comment by Jrawke** [comment]
oh, wait I think I was able to. Microphone is crashing but audio playback seems fine.

**Comment by Jrawke** [comment]
https://github.com/Jrawke/mumbleExpress/commit/456777912c5400574f9f4835217ffbed1f58e2f2 fixed

Basically, all these things are breaking because we have variables declared in global scope when they shouldn't be. The 'use strict' directive is why we are seeing these errors now. I'll look into using a JS linter to catch all these things at once.

**Comment by Jrawke** [comment]
I'll bet this isn't working because some audio processing object is getting garbage collected. That would explain why it works for a short while on Firefox

**Comment by Jrawke** [comment]
This also makes sense because I removed some things from global scope, so I'll bet important things are getting destroyed 
On Dec 19, 2015 7:09 PM, Owen Horwitz <ohorwitz@ucla.edu> wrote:I'll bet this isn't working because some audio processing object is getting garbage collected. That would explain why it works for a short while on Firefox

**Comment by Jrawke** [comment]
still having problems with this, so reopening issue
